<h2 align='center'>Bag Of Words (BOW) -  Naive Bayes </h2>

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [7]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [8]:
df.shape

(5572, 3)

In [9]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [11]:
X_train.shape

(4457,)

In [12]:
X_test.shape

(1115,)

In [13]:
type(X_train)

pandas.core.series.Series

In [23]:
X_train

2608    :-) yeah! Lol. Luckily i didn't have a starrin...
5104    A Boy loved a gal. He propsd bt she didnt mind...
3283    Hey you around? I've got enough for a half + t...
2339                            Alright, see you in a bit
4983    Slept? I thinkThis time ( &lt;#&gt;  pm) is no...
                              ...                        
1052       Do u noe wat time e place dat sells 4d closes?
3764                   K.i will send in  &lt;#&gt;  min:)
3726                   Nothing spl..wat abt u and whr ru?
5249        K I'm leaving soon, be there a little after 9
906     Hey what's up charles sorry about the late reply.
Name: Message, Length: 4457, dtype: object

<h3>Bag of Words Representation</h3>

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7757 sparse matrix of type '<class 'numpy.int64'>'
	with 59239 stored elements in Compressed Sparse Row format>

In [18]:
X_train_cv.toarray()[:3][1]

array([0, 0, 0, ..., 0, 0, 0])

In [19]:
X_train_cv.shape

(4457, 7757)

In [20]:
v.get_feature_names_out()[1771]

'cheers'

In [22]:
v.vocabulary_

{'yeah': 7692,
 'lol': 4182,
 'luckily': 4251,
 'didn': 2305,
 'have': 3361,
 'starring': 6446,
 'role': 5799,
 'like': 4106,
 'you': 7718,
 'boy': 1481,
 'loved': 4223,
 'gal': 3065,
 'he': 3371,
 'propsd': 5457,
 'bt': 1551,
 'she': 6065,
 'didnt': 2306,
 'mind': 4483,
 'gv': 3288,
 'lv': 4267,
 'lttrs': 4248,
 'her': 3417,
 'frnds': 3015,
 'threw': 6875,
 'thm': 6860,
 'again': 872,
 'decided': 2205,
 'aproach': 1054,
 'dt': 2478,
 'time': 6907,
 'truck': 7055,
 'was': 7395,
 'speeding': 6372,
 'towards': 7007,
 'wn': 7575,
 'it': 3766,
 'about': 767,
 'hit': 3449,
 'girl': 3141,
 'ran': 5552,
 'hell': 3399,
 'saved': 5912,
 'asked': 1111,
 'hw': 3573,
 'cn': 1877,
 'run': 5844,
 'so': 6280,
 'fast': 2783,
 'replied': 5699,
 'boost': 1445,
 'is': 3755,
 'secret': 5966,
 'of': 4888,
 'my': 4667,
 'energy': 2595,
 'instantly': 3704,
 'shouted': 6117,
 'our': 5002,
 'thy': 6892,
 'lived': 4149,
 'happily': 3334,
 '2gthr': 391,
 'drinking': 2455,
 'evrydy': 2691,
 'moral': 4586,
 'story

In [24]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [25]:
np.where(X_train_np[0]!=0)

(array([2305, 3361, 4106, 4182, 4251, 5799, 6446, 7692, 7718]),)

In [31]:
X_train

2608    :-) yeah! Lol. Luckily i didn't have a starrin...
5104    A Boy loved a gal. He propsd bt she didnt mind...
3283    Hey you around? I've got enough for a half + t...
2339                            Alright, see you in a bit
4983    Slept? I thinkThis time ( &lt;#&gt;  pm) is no...
                              ...                        
1052       Do u noe wat time e place dat sells 4d closes?
3764                   K.i will send in  &lt;#&gt;  min:)
3726                   Nothing spl..wat abt u and whr ru?
5249        K I'm leaving soon, be there a little after 9
906     Hey what's up charles sorry about the late reply.
Name: Message, Length: 4457, dtype: object

In [55]:
X_train[:10][5104]

'A Boy loved a gal. He propsd bt she didnt mind. He gv lv lttrs, Bt her frnds threw thm. Again d boy decided 2 aproach d gal , dt time a truck was speeding towards d gal. Wn it was about 2 hit d girl,d boy ran like hell n saved her. She asked \'hw cn u run so fast?\' D boy replied "Boost is d secret of my energy" n instantly d girl shouted "our energy" n Thy lived happily 2gthr drinking boost evrydy Moral of d story:- I hv free msgs:D;): gud ni8'

<h3>Train the naive bayes model</h3>

In [37]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [40]:
# X_test
X_test_cv = v.transform(X_test)
X_test_cv

<1115x7757 sparse matrix of type '<class 'numpy.int64'>'
	with 13849 stored elements in Compressed Sparse Row format>

<h3>Evaluate Performance</h3>

In [41]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       964
           1       0.97      0.91      0.94       151

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [48]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

<h3>Train the model using sklearn pipeline and reduce number of lines of code</h3>

In [50]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [51]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [52]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       964
           1       0.97      0.91      0.94       151

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.98      0.98      0.98      1115

